[project]
name = "depth"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.9"
dependencies = [
    "numpy>=2.0.2",
    "opencv-contrib-python>=4.11.0.86",
    "timm==0.6.7",
    "torch>=2.8.0",
    "ultralytics>=8.3.228",
]
